apiVersion: apps/v1
kind: Deployment
metadata:
    name: pihole
    namespace: homelab
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pihole
    template:
        metadata:
            labels:
                app: pihole
        spec:
            securityContext:
                seccompProfile:
                    type: RuntimeDefault
            containers:
                - name: pihole
                  image: pihole/pihole:latest
                  securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                          drop:
                              - ALL
                          add:
                              - NET_BIND_SERVICE
                              - NET_RAW
                              - NET_ADMIN
                  env:
                      - name: TZ
                        value: Europe/Kyiv
                      - name: DNSMASQ_USER
                        value: root
                      - name: WEBPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: pihole-credentials
                                key: WEBPASSWORD
                  ports:
                      - name: web
                        containerPort: 80
                      - name: dns-tcp
                        containerPort: 53
                        protocol: TCP
                      - name: dns-udp
                        containerPort: 53
                        protocol: UDP
                  resources:
                      requests:
                          cpu: 100m
                          memory: 128Mi
                      limits:
                          cpu: "1"
                          memory: 512Mi
                  volumeMounts:
                      - name: pihole-data
                        mountPath: /etc/pihole
                      - name: dnsmasq-data
                        mountPath: /etc/dnsmasq.d
            volumes:
                - name: pihole-data
                  persistentVolumeClaim:
                      claimName: pihole-pvc
                - name: dnsmasq-data
                  emptyDir: {}
