---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-credentials
  namespace: homelab
spec:
  encryptedData:
    WEBPASSWORD: AgAdAUUT+fGWhJ5gKY//19bYWGb7u7UXPLviT5WxQcx5YNoGFDgqERa+Ss8iyil87wDr0bAu6o+9V3PEsJeqB47tc3J7l88W2rS1z/SZW8WjqCIY0boPYrLqax+XHdcxZDMZvS7e1crWpEtLE4nxWfOnItlC4CNvsK7702xdgGPIf/Cm4zQjTKQx3RourhCcX8a/f8yBS1O81e1vFirkjWFJv7YPkYkbccO0gU7p/7PIpmDEm8rZ36DOX1I4w7NtklnBpARfCQvZDnM4LqL9vXH9anGc7/t+qzo6IiDlly1Xr8WyBpk40LQDE1BGX5AouZpYlYkrvJVx4bXYi6cYX6YWHVLrLHZV5s7fAEKUgINYGB3IuAUaY7rHOxlz4TdvFa/jTByVn++vuvUYQ7oLJiT024j9wKTsDblbpsfNqdKHXU3VM+0pkvqAsX723sJWJQSm/BaZ+IcwmaHip+G1pReTENblO4b/KxfBRuc0QpFKe/pjLdYIBYa1kdfM7owAZY3y0M4c95Q6QEy8scodmIBGXIEZhbgE4ArIdG2uou2mxr7hmidwkKLTrKLMxHht/JXjiYBb6clwlKr93od/FmANY0Q429bIEb/lQDUhxEBZjCTe+GiSxLdlcXYNtPgbHyGRiDScc9FVx+mmzDdf15sDU7o3sKRJ541Apj5XQ/C7XwJjESRLK36i2XU8jHyANUCRJVzfTaOc7AGNofP39yV9MaWSdDLPgfO7EL9+8nEruA==
  template:
    metadata:
      name: pihole-credentials
      namespace: homelab
