apiVersion: v1
kind: Service
metadata:
  name: nginx-gitops
  namespace: homelab
spec:
  type: ClusterIP
  selector:
    app: nginx-gitops
  ports:
    - name: http
      port: 80
      targetPort: 80
