---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: default
spec:
  encryptedData:
    WEBPASSWORD: AgB6JcZydc8DU/efOX+xky7L59yqk7ltHq+HqJkGjD2kdp3odCZnMlJ9oUed5ZVEWT10LbrFu4wnwBZeJfqF5f/IKJh2Ko6YrVltbwdPQca/pBCytkVASonTbu4FeV/wzZ17obrJ7dZF3WwnQszD/LiqchZZ0aaVM8t/ZAuLWpwwZp1bYPauju5YzKBPqhZmC5K6Ync+JDg0ZAZNgoTdV2n0f9swDNEaZsPfcKAMXC54i9RG3nx5xIz/EJdWKZVT+l3V3fuuEHTh5XcdjmW+4zlBYoz9vMOsjSDsOERBwe27SOEX5LqQVIqeF34F97NCuuJyieU7rBVfFX8RyepRqq+CPA89VLjwh8G4BdMAE3kZ4QfonE8DS8gTKvC9I2tSfaUTxCDRCti9M9rJDfS5MwoXciQgogpDkMI5V2RpcJBZrj+dpGv47r6Ikl3GR64ze/9X2i2ZBizrrJ4xsw/VMR8OTWU6EnZLF00wR9Y++5MdXAnteklfFUilJx8gqRhsiu1kBhCMoPDRewWoa1nwieYrTkFW/qKFfPrxJRDjhIxG/aF6LufSEJO1Bdv9bHYTqBVHce0iiaf/yiCQGEG2DMkgT153wOuvgANDg6YdDl/A0IrBhpzSjSnJ1uCMVu1vDZ1p29fdXfep2NPIvY66dvZ+DRVt4mFrfiV0v74tKG57AKiOJkI5VtCs8Rq5vptDJyCO4InIizkfxw==
  template:
    metadata:
      name: pihole-secret
      namespace: default
