apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: rancher-charts
    namespace: flux-system
spec:
    interval: 1h
    url: https://charts.rancher.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: local-path-provisioner
    namespace: flux-system
spec:
    interval: 30m
    targetNamespace: local-path-storage
    install:
        createNamespace: true
    chart:
        spec:
            chart: local-path-provisioner
            version: "0.0.28"
            sourceRef:
                kind: HelmRepository
                name: rancher-charts
                namespace: flux-system
            interval: 12h
