apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-production
  namespace: flux-system
spec:
  interval: 10m
  path: ./homelab-gitops/clusters/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
