apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - cert-manager.yaml
    - cert-issuer-selfsigned.yaml
    - homepage.yaml
    - ingress-apps.yaml
    - ingress-nginx.yaml
    - loki.yaml
