apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: grafana
    namespace: flux-system
spec:
    interval: 1h
    url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: loki
    namespace: flux-system
spec:
    interval: 30m
    targetNamespace: monitoring
    install:
        createNamespace: true
    chart:
        spec:
            chart: loki-stack
            version: "2.*"
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: flux-system
            interval: 12h
  values:
    promtail:
      enabled: true
    grafana:
      enabled: false
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: loki-datasource
    namespace: monitoring
    labels:
        grafana_datasource: "1"
data:
    loki-datasource.yaml: |-
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://monitoring-loki.monitoring.svc.cluster.local:3100
            isDefault: false
