apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          env:
            - name: TZ
              value: Europe/Kyiv
          ports:
            - name: http
              containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-pvc
